services:
  firebird:
    image: firebirdsql/firebird:5-noble
    container_name: firebird
    restart: always 
    ports:
      - "3050:3050"  
    environment:
      - FIREBIRD_ROOT_PASSWORD=zaq1@WSX
      - FIREBIRD_USER=AdminRoot
      - FIREBIRD_PASSWORD=zaq1@WSX
      - FIREBIRD_DATABASE=mirror.fdb
      - FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8
    volumes:
      - ./databaseDirectory:/var/lib/firebird/data